name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# ป้องกันคิวซ้อน — ถ้ามี commit ใหม่มา จะยกเลิกรันเก่าที่ค้างอยู่
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test on Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 22] # ทดสอบหลายเวอร์ชันให้มั่นใจ (LTS/Current)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install deps (CI mode)
        run: npm ci

      - name: Run tests
        run: npm run test

      # เก็บผลทดสอบ/coverage (เผื่อคุณยุ้ยเพิ่มภายหลัง)
      # - name: Upload coverage
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: coverage-${{ matrix.node }}
      #     path: coverage/
